version: "3.2"

services:
  php:
    image: elasticms/base-php-nginx-dev:7.3
    container_name: php
    ports:
      - 9000:9000
    networks:
      - es5net
    volumes:
      - "${GIT_PATH}:/usr/share/nginx/html"
      - ./nginx:/etc/nginx/sites-enabled
      #- ./bin:/usr/bin
      - phpfpm:/var/run/php-fpm
  tika:
    image: apache/tika
    container_name: tika
    ports:
      - 9998:9998
    networks:
      - es5net


  mysql_emseu:
    image: docker.io/mysql/mysql-server:5.7
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=emseu
      - DEBUG=false
    volumes:
      - data_mysql_emseu:/var/lib/mysql
    networks:
      - es5net
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es5data1:/usr/share/elasticsearch/data
    ports:
      - 9205:9200
    networks:
      - es5net
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es5data2:/usr/share/elasticsearch/data
    networks:
      - es5net

volumes:
  data_mysql_emseu:
    driver: local
  phpfpm:
    driver: local
  es5data1:
    driver: local
  es5data2:
    driver: local

networks:
  es5net: